services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node:lts
    working_dir: /app
    ports:
      - "2204:2204"
    depends_on:
      - postgres
    env_file:
      - path: ./env
        required: false
    restart: always

  postgres:
    build:
      context: .
      dockerfile: ./postgres.Dockerfile 
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=N@mnguyen147159
    - POSTGRES_DB=Spotify_Backend

    env_file:
      - path: ./.env
        required: false
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
